import Config
config :live_vue, vite_host: "http://localhost:5173", ssr_module: LiveVue.SSR.ViteJS
config :ash, policies: [show_policy_breakdowns?: true]

# Keep Ash codegen explicit in this repo. The default AshPhoenix dev plug can
# offer a browser action that runs `mix ash.codegen --dev` and migrations from
# a request failure page, which is too eager for this workspace.
config :jido_code, ash_codegen_status_check?: false

config :git_ops,
  mix_project: JidoCode.MixProject,
  changelog_file: "CHANGELOG.md",
  repository_url: "https://github.com/epic-creative/jido_code",
  manage_mix_version?: true,
  version_tag_prefix: "v"

# Configure your database
config :jido_code, JidoCode.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "jido_code_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :jido_code, JidoCodeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "EhyC3sZ9xWoeOHM5EvgUdSpa/MLgrYU39T1WVQ3nEioHBm9wa/kTrLj62/Zz1Aek",
  watchers: [vite: {PhoenixVite.Npm, :run, [:vite, ~w(dev)]}],
  static_url: [host: "localhost", port: 5173]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :jido_code, JidoCodeWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/jido_code_web/router\.ex$",
      ~r"lib/jido_code_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :jido_code, dev_routes: true, token_signing_secret: "z6qnBdiiFJ1LqYrmIirMWGK3GwB+ltgL"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Ontology configuration (optional - requires elixir_ontologies package)
# When elixir_ontologies is available, uncomment to enable:
# config :jido_code, :ontology_enabled, true

# AgentOS configuration
config :jido_code,
  # AgentOS kernel manager configuration
  agent_os_kernel_supervisor: JidoCode.AgentOS.Manager.Supervisor,
  agent_os_registry: JidoCode.AgentOS.Manager.Registry,
  # Ecto persistence for kernels and pods
  agent_os_persistence: [
    adapter: Jido.Ecto.Storage,
    repo: JidoCode.Repo
  ],
  # Source code graph configuration (enabled in dev with conservative defaults)
  source_code_graph_enabled: true,
  # 5 minutes
  source_code_graph_analysis_timeout_ms: 300_000,
  # 2 minutes
  source_code_graph_load_timeout_ms: 120_000,
  # 30 seconds
  source_code_graph_query_timeout_ms: 30_000,
  source_code_graph_file_watcher_enabled: true,
  source_code_graph_file_watcher_debounce_ms: 500,
  source_code_graph_file_watcher_max_pending_paths: 500,
  source_code_graph_auto_refresh_enabled: true,
  source_code_graph_refresh_debounce_ms: 250,
  source_code_graph_refresh_max_coalesce_ms: 2_500,
  source_code_graph_refresh_max_pending_paths: 500,
  source_code_graph_auto_refresh_missing_graph_policy: :skip,
  source_code_graph_auto_refresh_max_attempts: 1,
  source_code_graph_max_retries: 3,
  source_code_graph_retry_backoff_ms: 1000,
  source_code_graph_max_file_count: 10_000,
  source_code_graph_max_graph_size_mb: 500,
  source_code_graph_allow_partial_results: false,
  # Memory graph configuration (enabled in dev with conservative defaults)
  memory_graph_enabled: true,
  # 30 seconds - TripleStore operations
  memory_graph_store_timeout_ms: 30_000,
  # 1 minute - SPARQL queries
  memory_graph_query_timeout_ms: 60_000,
  # 2 minutes - ontology validation
  memory_graph_validation_timeout_ms: 120_000,
  # 5 minutes - recovery operations
  memory_graph_recovery_timeout_ms: 300_000,
  # maximum retry attempts for transient failures
  memory_graph_max_retries: 3,
  # maximum retry attempts for write operations
  memory_graph_max_write_retries: 2,
  # base backoff time in milliseconds
  memory_graph_retry_backoff_ms: 1000,
  # maximum graph size in MB (10 GB)
  memory_graph_max_graph_size_mb: 10_000,
  # maximum query result count
  memory_graph_max_query_results: 10_000,
  # maximum concurrent write operations
  memory_graph_max_concurrent_operations: 50
