defmodule JidoCode.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Legacy autogenerated snapshot migration retained as a no-op.

  The control-plane, governance, and conversation resources that appeared in the
  original autogenerated snapshot were later split into explicit hand-authored
  migrations that already run earlier in the sequence. Leaving the generated DDL
  in place causes `mix ecto.reset` to fail on a fresh database when it tries to
  recreate tables such as `external_objects`.
  """

  use Ecto.Migration

  def up, do: :ok

  def down, do: :ok
end
