defmodule JidoCode.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    ALTER TABLE users
    ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false
    """)
  end

  def down do
    execute("""
    ALTER TABLE users
    DROP COLUMN IF EXISTS is_admin
    """)
  end
end
