defmodule JidoCode.Repo.Migrations.LocalIdentityLinking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_identities) do
      add :first_authenticated_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:user_identities) do
      remove :first_authenticated_at
    end
  end
end
