defmodule JidoCode.Repo.Migrations.ProviderAuthFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :provider_host, :text, null: false
      add :provider_subject, :text, null: false
      add :provider_login, :text
      add :provider_email, :citext
      add :email_verified, :boolean, null: false, default: false
      add :last_authenticated_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_identities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:user_identities, [:provider, :provider_host, :provider_subject],
             name: "user_identities_unique_provider_subject_index"
           )

    create table(:auth_provider_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :provider_host, :text, null: false
      add :enabled, :boolean, null: false, default: false
      add :login_enabled, :boolean, null: false, default: false
      add :allowlist_mode, :text, null: false, default: "none"
      add :allowlist_values, {:array, :text}, null: false, default: []
      add :broker_issuer, :text
      add :broker_audience, :text
      add :broker_base_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:auth_provider_configs, [:provider, :provider_host],
             name: "auth_provider_configs_unique_provider_host_index"
           )
  end

  def down do
    drop_if_exists unique_index(:auth_provider_configs, [:provider, :provider_host],
                     name: "auth_provider_configs_unique_provider_host_index"
                   )

    drop table(:auth_provider_configs)

    drop_if_exists unique_index(:user_identities, [:provider, :provider_host, :provider_subject],
                     name: "user_identities_unique_provider_subject_index"
                   )

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    drop table(:user_identities)
  end
end
