defmodule JidoCode.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:external_objects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :object_type, :text, null: false
      add :external_id, :text, null: false
      add :canonical_key, :text, null: false
      add :canonical_reference, :text
      add :title, :text
      add :url, :text
      add :status, :text
      add :payload, :map, null: false, default: %{}
      add :source_metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :managed_repo_id, :uuid
    end

    create table(:managed_repos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:external_objects) do
      modify :managed_repo_id,
             references(:managed_repos,
               column: :id,
               name: "external_objects_managed_repo_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:external_objects, [:canonical_key],
             name: "external_objects_unique_canonical_key_index"
           )

    alter table(:managed_repos) do
      add :display_name, :text, null: false
      add :legacy_project_id, :uuid
      add :workspace_settings, :map, null: false, default: %{}
      add :execution_settings, :map, null: false, default: %{}
      add :integration_settings, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_repo_id, :uuid, null: false
    end

    alter table(:workflow_runs) do
      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "workflow_runs_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:observations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false
      add :category, :text, null: false
      add :summary, :text, null: false
      add :payload, :map, null: false, default: %{}
      add :source_metadata, :map, null: false, default: %{}
      add :captured_by, :map, null: false, default: %{}
      add :observed_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "observations_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :external_object_id,
          references(:external_objects,
            column: :id,
            name: "observations_external_object_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :category, :text, null: false
      add :summary, :text, null: false
      add :correlation_key, :text, null: false
      add :payload, :map, null: false, default: %{}
      add :source_metadata, :map, null: false, default: %{}
      add :occurred_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "events_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :external_object_id,
          references(:external_objects,
            column: :id,
            name: "events_external_object_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :observation_id,
          references(:observations,
            column: :id,
            name: "events_observation_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :intake_id, :uuid
    end

    create table(:intakes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:events) do
      modify :intake_id,
             references(:intakes,
               column: :id,
               name: "events_intake_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:intakes) do
      add :channel, :text, null: false
      add :intent, :text, null: false
      add :payload, :map, null: false, default: %{}
      add :source_metadata, :map, null: false, default: %{}
      add :requested_by, :map, null: false, default: %{}
      add :received_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "intakes_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "active"
      add :scope, :text, null: false
      add :attachment_mode, :text, null: false
      add :source, :text, null: false
      add :title, :text
      add :objective, :text
      add :initiating_actor, :map, null: false, default: %{}
      add :source_metadata, :map, null: false, default: %{}
      add :conversation_metadata, :map, null: false, default: %{}
      add :started_at, :utc_datetime_usec, null: false
      add :last_activity_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "conversations_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :work_item_id, :uuid
    end

    create table(:runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :legacy_project_id, :uuid, null: false
      add :run_id, :text, null: false
      add :workflow_name, :text, null: false
      add :workflow_version, :bigint, null: false
      add :status, :text, null: false, default: "pending"
      add :current_step, :text, null: false, default: "unknown"
      add :current_stage, :text, null: false, default: "repo_attach"
      add :governed_stages, {:array, :text}, null: false
      add :stage_statuses, :map, null: false, default: %{}
      add :trigger, :map, null: false, default: %{}
      add :inputs, :map, null: false, default: %{}
      add :input_metadata, :map, null: false, default: %{}
      add :initiating_actor, :map, null: false, default: %{}
      add :execution_engine, :text, null: false, default: "jido_runic"
      add :workflow_state_ref, :map, null: false, default: %{}
      add :run_metadata, :map, null: false, default: %{}
      add :work_item_id, :uuid
      add :retry_of_run_id, :text
      add :retry_attempt, :bigint, null: false, default: 1
      add :retry_lineage, {:array, :map}, null: false, default: []
      add :started_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workflow_run_id,
          references(:workflow_runs,
            column: :id,
            name: "runs_workflow_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "runs_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :execution_profile_id, :uuid
    end

    create table(:evidence_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :run_id, :uuid, null: false
      add :managed_repo_id, :uuid, null: false
      add :work_item_id, :uuid
      add :key, :text, null: false
      add :evidence_type, :text, null: false
      add :summary, :text, null: false
      add :evidence_details, :map, null: false, default: %{}
      add :source, :text, null: false, default: "workflow_run"
      add :recorded_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:evidence_records, [:run_id, :key],
             name: "evidence_records_unique_run_key_index"
           )

    create table(:conversation_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "active"
      add :admission_paused, :boolean, null: false, default: false
      add :child_execution_paused, :boolean, null: false, default: false
      add :active_turn_id, :text
      add :active_child_work_id, :text
      add :queued_turn_ids, {:array, :text}, null: false, default: []
      add :turns, {:array, :map}, null: false, default: []
      add :child_works, {:array, :map}, null: false, default: []
      add :control_history, {:array, :map}, null: false, default: []
      add :last_event_sequence, :bigint, null: false, default: 0
      add :event_count, :bigint, null: false, default: 0
      add :events, {:array, :map}, null: false, default: []
      add :shared_context, :map, null: false, default: %{}
      add :captured_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_snapshots_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "conversation_snapshots_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :work_item_id, :uuid
    end

    create table(:assessments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :category, :text, null: false
      add :summary, :text, null: false
      add :priority, :text, null: false
      add :urgency, :text, null: false
      add :recommended_action, :text, null: false
      add :rationale, :text
      add :inputs, :map, null: false, default: %{}
      add :assessment_metadata, :map, null: false, default: %{}
      add :assessed_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "assessments_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :event_id,
          references(:events,
            column: :id,
            name: "assessments_event_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :external_object_id,
          references(:external_objects,
            column: :id,
            name: "assessments_external_object_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:source_repos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:managed_repos) do
      modify :source_repo_id,
             references(:source_repos,
               column: :id,
               name: "managed_repos_source_repo_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:managed_repos, [:legacy_project_id],
             name: "managed_repos_unique_legacy_project_id_index"
           )

    create unique_index(:managed_repos, [:source_repo_id],
             name: "managed_repos_unique_source_repo_index"
           )

    alter table(:source_repos) do
      add :provider, :text, null: false
      add :owner, :text, null: false
      add :name, :text, null: false
      add :full_name, :text, null: false
      add :default_branch, :text, null: false, default: "main"
      add :source_metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:source_repos, [:provider, :full_name],
             name: "source_repos_unique_provider_full_name_index"
           )

    create table(:conversation_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sequence, :bigint, null: false
      add :name, :text, null: false
      add :actor, :map, null: false, default: %{}
      add :message_id, :text
      add :turn_id, :text
      add :child_work_id, :text
      add :tool_call_id, :text
      add :correlation, :map, null: false, default: %{}
      add :payload, :map, null: false, default: %{}
      add :occurred_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_events_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:conversation_events, [:conversation_id, :sequence],
             name: "conversation_events_unique_conversation_sequence_index"
           )

    create table(:posture_checks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :dimension, :text, null: false
      add :value, :text, null: false
      add :summary, :text, null: false
      add :details, :map, null: false, default: %{}
      add :source, :text, null: false, default: "posture_bridge"
      add :threat_level, :text, null: false, default: "none"
      add :escalation_mode, :text, null: false, default: "none"
      add :checked_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :repo_posture_id, :uuid
      add :managed_repo_id, :uuid, null: false
      add :observation_id, :uuid
      add :assessment_id, :uuid
      add :evidence_id, :uuid
    end

    create table(:decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :decision_key, :text, null: false
      add :run_id, :uuid, null: false
      add :change_request_id, :uuid
      add :managed_repo_id, :uuid, null: false
      add :work_item_id, :uuid
      add :decision, :text, null: false
      add :actor, :map, null: false, default: %{}
      add :rationale, :text
      add :evidence_ids, {:array, :uuid}, null: false, default: []
      add :decision_metadata, :map, null: false, default: %{}
      add :decided_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:decisions, [:decision_key], name: "decisions_unique_decision_key_index")

    create table(:policy_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false, default: "default"
      add :review_policy, :map, null: false
      add :policy_metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "policy_sets_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:policy_sets, [:managed_repo_id, :name],
             name: "policy_sets_unique_managed_repo_name_index"
           )

    create table(:change_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :run_id, :uuid, null: false
      add :managed_repo_id, :uuid, null: false
      add :work_item_id, :uuid
      add :status, :text, null: false, default: "open"
      add :summary, :text, null: false
      add :review_context, :map, null: false, default: %{}
      add :request_metadata, :map, null: false, default: %{}
      add :evidence_ids, {:array, :uuid}, null: false, default: []
      add :requested_at, :utc_datetime_usec, null: false
      add :resolved_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:change_requests, [:run_id], name: "change_requests_unique_run_index")

    create table(:execution_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:runs) do
      modify :execution_profile_id,
             references(:execution_profiles,
               column: :id,
               name: "runs_execution_profile_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:runs, [:managed_repo_id, :run_id],
             name: "runs_unique_managed_repo_run_id_index"
           )

    create unique_index(:runs, [:workflow_run_id], name: "runs_unique_workflow_run_index")

    alter table(:execution_profiles) do
      add :name, :text, null: false, default: "default"
      add :sandbox_profile, :map, null: false, default: %{}
      add :repo_prep_plan, {:array, :text}, null: false
      add :validation_plan, {:array, :text}, null: false
      add :governed_stages, {:array, :text}, null: false
      add :checkpoint_strategy, :text, null: false, default: "resume_from_runic_state"
      add :resume_strategy, :text, null: false, default: "resume_from_runic_state"
      add :profile_metadata, :map, null: false, default: %{}
      add :source, :text, null: false, default: "managed_repo.execution_settings"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "execution_profiles_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:execution_profiles, [:managed_repo_id, :name],
             name: "execution_profiles_unique_managed_repo_name_index"
           )

    create table(:work_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:conversations) do
      modify :work_item_id,
             references(:work_items,
               column: :id,
               name: "conversations_work_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conversation_snapshots) do
      modify :work_item_id,
             references(:work_items,
               column: :id,
               name: "conversation_snapshots_work_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:conversation_snapshots, [:conversation_id],
             name: "conversation_snapshots_unique_conversation_index"
           )

    alter table(:work_items) do
      add :category, :text, null: false
      add :status, :text, null: false, default: "open"
      add :priority, :text, null: false
      add :recommended_action, :text, null: false
      add :summary, :text, null: false
      add :dedup_key, :text, null: false
      add :initiating_actor, :map, null: false, default: %{}
      add :work_metadata, :map, null: false, default: %{}
      add :audit_log, {:array, :map}, null: false, default: []
      add :opened_at, :utc_datetime_usec, null: false
      add :last_assessed_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "work_items_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :assessment_id,
          references(:assessments,
            column: :id,
            name: "work_items_assessment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "work_items_event_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :external_object_id,
          references(:external_objects,
            column: :id,
            name: "work_items_external_object_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :observation_id,
          references(:observations,
            column: :id,
            name: "work_items_observation_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :intake_id,
          references(:intakes,
            column: :id,
            name: "work_items_intake_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:repo_postures, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:posture_checks) do
      modify :repo_posture_id,
             references(:repo_postures,
               column: :id,
               name: "posture_checks_repo_posture_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :managed_repo_id,
             references(:managed_repos,
               column: :id,
               name: "posture_checks_managed_repo_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :observation_id,
             references(:observations,
               column: :id,
               name: "posture_checks_observation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :assessment_id,
             references(:assessments,
               column: :id,
               name: "posture_checks_assessment_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :evidence_id,
             references(:evidence_records,
               column: :id,
               name: "posture_checks_evidence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:posture_checks, [:managed_repo_id, :dimension],
             name: "posture_checks_unique_managed_repo_dimension_index"
           )

    alter table(:repo_postures) do
      add :summary, :text, null: false
      add :overall_trust, :text, null: false
      add :execution_readiness, :text, null: false
      add :validation_reliability, :text, null: false
      add :review_burden, :text, null: false
      add :drift_rate, :text, null: false
      add :recovery_resilience, :text, null: false
      add :requirements_confidence, :text, null: false
      add :supervision_mode, :text, null: false, default: "guided"
      add :escalation_status, :text, null: false, default: "normal"

      add :algedonic_check_id,
          references(:posture_checks,
            column: :id,
            name: "repo_postures_algedonic_check_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :contributing_check_ids, {:array, :uuid}, null: false, default: []
      add :posture_metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :managed_repo_id,
          references(:managed_repos,
            column: :id,
            name: "repo_postures_managed_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:repo_postures, [:managed_repo_id],
             name: "repo_postures_unique_managed_repo_index"
           )
  end

  def down do
    drop_if_exists unique_index(:repo_postures, [:managed_repo_id],
                     name: "repo_postures_unique_managed_repo_index"
                   )

    drop constraint(:repo_postures, "repo_postures_algedonic_check_id_fkey")

    drop constraint(:repo_postures, "repo_postures_managed_repo_id_fkey")

    alter table(:repo_postures) do
      remove :managed_repo_id
      remove :updated_at
      remove :inserted_at
      remove :posture_metadata
      remove :contributing_check_ids
      remove :algedonic_check_id
      remove :escalation_status
      remove :supervision_mode
      remove :requirements_confidence
      remove :recovery_resilience
      remove :drift_rate
      remove :review_burden
      remove :validation_reliability
      remove :execution_readiness
      remove :overall_trust
      remove :summary
    end

    drop_if_exists unique_index(:posture_checks, [:managed_repo_id, :dimension],
                     name: "posture_checks_unique_managed_repo_dimension_index"
                   )

    drop constraint(:posture_checks, "posture_checks_repo_posture_id_fkey")

    drop constraint(:posture_checks, "posture_checks_managed_repo_id_fkey")

    drop constraint(:posture_checks, "posture_checks_observation_id_fkey")

    drop constraint(:posture_checks, "posture_checks_assessment_id_fkey")

    drop constraint(:posture_checks, "posture_checks_evidence_id_fkey")

    alter table(:posture_checks) do
      modify :evidence_id, :uuid
      modify :assessment_id, :uuid
      modify :observation_id, :uuid
      modify :managed_repo_id, :uuid
      modify :repo_posture_id, :uuid
    end

    drop table(:repo_postures)

    drop constraint(:work_items, "work_items_managed_repo_id_fkey")

    drop constraint(:work_items, "work_items_assessment_id_fkey")

    drop constraint(:work_items, "work_items_event_id_fkey")

    drop constraint(:work_items, "work_items_external_object_id_fkey")

    drop constraint(:work_items, "work_items_observation_id_fkey")

    drop constraint(:work_items, "work_items_intake_id_fkey")

    alter table(:work_items) do
      remove :intake_id
      remove :observation_id
      remove :external_object_id
      remove :event_id
      remove :assessment_id
      remove :managed_repo_id
      remove :updated_at
      remove :inserted_at
      remove :last_assessed_at
      remove :opened_at
      remove :audit_log
      remove :work_metadata
      remove :initiating_actor
      remove :dedup_key
      remove :summary
      remove :recommended_action
      remove :priority
      remove :status
      remove :category
    end

    drop_if_exists unique_index(:conversation_snapshots, [:conversation_id],
                     name: "conversation_snapshots_unique_conversation_index"
                   )

    drop constraint(:conversation_snapshots, "conversation_snapshots_work_item_id_fkey")

    alter table(:conversation_snapshots) do
      modify :work_item_id, :uuid
    end

    drop constraint(:conversations, "conversations_work_item_id_fkey")

    alter table(:conversations) do
      modify :work_item_id, :uuid
    end

    drop table(:work_items)

    drop_if_exists unique_index(:execution_profiles, [:managed_repo_id, :name],
                     name: "execution_profiles_unique_managed_repo_name_index"
                   )

    drop constraint(:execution_profiles, "execution_profiles_managed_repo_id_fkey")

    alter table(:execution_profiles) do
      remove :managed_repo_id
      remove :updated_at
      remove :inserted_at
      remove :source
      remove :profile_metadata
      remove :resume_strategy
      remove :checkpoint_strategy
      remove :governed_stages
      remove :validation_plan
      remove :repo_prep_plan
      remove :sandbox_profile
      remove :name
    end

    drop_if_exists unique_index(:runs, [:workflow_run_id], name: "runs_unique_workflow_run_index")

    drop_if_exists unique_index(:runs, [:managed_repo_id, :run_id],
                     name: "runs_unique_managed_repo_run_id_index"
                   )

    drop constraint(:runs, "runs_execution_profile_id_fkey")

    alter table(:runs) do
      modify :execution_profile_id, :uuid
    end

    drop table(:execution_profiles)

    drop_if_exists unique_index(:change_requests, [:run_id],
                     name: "change_requests_unique_run_index"
                   )

    drop table(:change_requests)

    drop_if_exists unique_index(:policy_sets, [:managed_repo_id, :name],
                     name: "policy_sets_unique_managed_repo_name_index"
                   )

    drop constraint(:policy_sets, "policy_sets_managed_repo_id_fkey")

    drop table(:policy_sets)

    drop_if_exists unique_index(:decisions, [:decision_key],
                     name: "decisions_unique_decision_key_index"
                   )

    drop table(:decisions)

    drop table(:posture_checks)

    drop_if_exists unique_index(:conversation_events, [:conversation_id, :sequence],
                     name: "conversation_events_unique_conversation_sequence_index"
                   )

    drop constraint(:conversation_events, "conversation_events_conversation_id_fkey")

    drop table(:conversation_events)

    drop_if_exists unique_index(:source_repos, [:provider, :full_name],
                     name: "source_repos_unique_provider_full_name_index"
                   )

    alter table(:source_repos) do
      remove :updated_at
      remove :inserted_at
      remove :source_metadata
      remove :default_branch
      remove :full_name
      remove :name
      remove :owner
      remove :provider
    end

    drop_if_exists unique_index(:managed_repos, [:source_repo_id],
                     name: "managed_repos_unique_source_repo_index"
                   )

    drop_if_exists unique_index(:managed_repos, [:legacy_project_id],
                     name: "managed_repos_unique_legacy_project_id_index"
                   )

    drop constraint(:managed_repos, "managed_repos_source_repo_id_fkey")

    alter table(:managed_repos) do
      modify :source_repo_id, :uuid
    end

    drop table(:source_repos)

    drop constraint(:assessments, "assessments_managed_repo_id_fkey")

    drop constraint(:assessments, "assessments_event_id_fkey")

    drop constraint(:assessments, "assessments_external_object_id_fkey")

    drop table(:assessments)

    drop constraint(:conversation_snapshots, "conversation_snapshots_conversation_id_fkey")

    drop constraint(:conversation_snapshots, "conversation_snapshots_managed_repo_id_fkey")

    drop table(:conversation_snapshots)

    drop_if_exists unique_index(:evidence_records, [:run_id, :key],
                     name: "evidence_records_unique_run_key_index"
                   )

    drop table(:evidence_records)

    drop constraint(:runs, "runs_workflow_run_id_fkey")

    drop constraint(:runs, "runs_managed_repo_id_fkey")

    drop table(:runs)

    drop constraint(:conversations, "conversations_managed_repo_id_fkey")

    drop table(:conversations)

    drop constraint(:intakes, "intakes_managed_repo_id_fkey")

    alter table(:intakes) do
      remove :managed_repo_id
      remove :updated_at
      remove :inserted_at
      remove :received_at
      remove :requested_by
      remove :source_metadata
      remove :payload
      remove :intent
      remove :channel
    end

    drop constraint(:events, "events_intake_id_fkey")

    alter table(:events) do
      modify :intake_id, :uuid
    end

    drop table(:intakes)

    drop constraint(:events, "events_managed_repo_id_fkey")

    drop constraint(:events, "events_external_object_id_fkey")

    drop constraint(:events, "events_observation_id_fkey")

    drop table(:events)

    drop constraint(:observations, "observations_managed_repo_id_fkey")

    drop constraint(:observations, "observations_external_object_id_fkey")

    drop table(:observations)

    drop constraint(:workflow_runs, "workflow_runs_managed_repo_id_fkey")

    alter table(:workflow_runs) do
      remove :managed_repo_id
    end

    alter table(:managed_repos) do
      remove :source_repo_id
      remove :updated_at
      remove :inserted_at
      remove :integration_settings
      remove :execution_settings
      remove :workspace_settings
      remove :legacy_project_id
      remove :display_name
    end

    drop_if_exists unique_index(:external_objects, [:canonical_key],
                     name: "external_objects_unique_canonical_key_index"
                   )

    drop constraint(:external_objects, "external_objects_managed_repo_id_fkey")

    alter table(:external_objects) do
      modify :managed_repo_id, :uuid
    end

    drop table(:managed_repos)

    drop table(:external_objects)
  end
end
