defmodule JidoCode.Repo.Migrations.AddProjectSourceIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      modify :github_full_name, :text, null: true
      add :source_kind, :text, null: false, default: "github"
      add :source_identifier, :text
      add :local_path, :text
    end

    execute("""
    UPDATE projects
    SET source_identifier = github_full_name
    WHERE source_kind = 'github'
      AND source_identifier IS NULL
      AND github_full_name IS NOT NULL
    """)

    create unique_index(:projects, [:source_kind, :source_identifier],
             name: "projects_unique_source_identity_index"
           )
  end

  def down do
    drop_if_exists unique_index(:projects, [:source_kind, :source_identifier],
                     name: "projects_unique_source_identity_index"
                   )

    alter table(:projects) do
      remove :local_path
      remove :source_identifier
      remove :source_kind
      modify :github_full_name, :text, null: false
    end
  end
end
